"""Non-self-certifying numeric-field and nonfinite-sentinel completeness tests."""

import copy
import json
import re
from pathlib import Path

import numpy as np
import pytest
from jsonschema import ValidationError
from scipy.optimize import OptimizeResult

import bistar_gp.m2cr.gates_v2 as gates
from bistar_gp.m2c_freeze import TOL_GRAD_ABS, TOL_GRAD_REL
from bistar_gp.m2cr.coordinates import storage_to_canonical_permutation
from bistar_gp.m2cr.records import (
    build_battery_record,
    build_curvature_record,
    build_per_node_record,
    build_two_start_optimizer_record,
    build_warm_start_ref,
    validate_fragment,
)
from bistar_gp.m2cr.serialization import (
    canonical_dumps,
    encode_float,
    encode_vector,
    is_nonfinite_sentinel,
)

SCHEMA_PATH = (
    Path(__file__).resolve().parents[1]
    / "docs"
    / "m2c_freeze"
    / "m2c_execution_record.schema_v1.json"
)
SCHEMA = json.loads(SCHEMA_PATH.read_text())
STORAGE_ORDER = (
    "SITE.outputscale",
    "SITE.base_kernel.lengthscale",
    "SITE.kernels.1.variance",
)
PERM = storage_to_canonical_permutation(STORAGE_ORDER)

# Hand-written fixtures are independent of canonical_dumps and encode_float.
GOLDEN_NEG_INF = '{"value":{"_nonfinite":"-inf"}}'
GOLDEN_POS_INF = '{"value":{"_nonfinite":"+inf"}}'
GOLDEN_NAN = '{"value":{"_nonfinite":"nan"}}'
GOLDEN_VECTOR = (
    '{"vector":[{"_nonfinite":"-inf"},{"_nonfinite":"+inf"},'
    '{"_nonfinite":"nan"}]}'
)
GOLDEN_TWO_START_OPTIMIZER_RECORD = (
    '{"agree":false,"agree_g":false,"agree_u":false,"both_success":false,'
    '"g_star":0.5,"grad_inf_norm":0.0,"reason":"warm result is non-finite",'
    '"restart_count":0,"starts":[{"attempts":[{"accepted":false,'
    '"finite":false,"g":{"_nonfinite":"-inf"},"grad_inf_norm":{'
    '"_nonfinite":"+inf"},"gradient":[{"_nonfinite":"+inf"},-0.0,{'
    '"_nonfinite":"nan"}],"is_jittered_restart":false,"message":"fixed 1",'
    '"reported_success":true,"start":[1.0,1.0,1.0],"stationary":false,'
    '"status":0,"u":[1.0,0.0,0.5]}],"label":"warm"},{"attempts":[{'
    '"accepted":true,"finite":true,"g":0.5,"grad_inf_norm":0.0,'
    '"gradient":[0.0,0.0,0.0],"is_jittered_restart":false,'
    '"message":"fixed 2","reported_success":true,"start":[-1.0,-1.0,-1.0],'
    '"stationary":true,"status":0,"u":[0.0,1.0,0.5]}],"label":"mode"}],'
    '"stop":true,"u_star":[0.0,1.0,0.5]}'
)
GOLDEN_BATTERY_RECORD = (
    '{"coordinates":[{"absolute_error":{"_nonfinite":"+inf"},"fd_step":{'
    '"_nonfinite":"nan"},"functional_value":{"_nonfinite":"nan"},'
    '"pass":false,"reference_value":{"_nonfinite":"+inf"},"role":"ls",'
    '"threshold":{"_nonfinite":"+inf"}},{"absolute_error":{'
    '"_nonfinite":"nan"},"fd_step":{"_nonfinite":"+inf"},'
    '"functional_value":{"_nonfinite":"+inf"},"pass":false,'
    '"reference_value":{"_nonfinite":"-inf"},"role":"os","threshold":{'
    '"_nonfinite":"+inf"}},{"absolute_error":{"_nonfinite":"-inf"},'
    '"fd_step":{"_nonfinite":"-inf"},"functional_value":{'
    '"_nonfinite":"-inf"},"pass":false,"reference_value":{'
    '"_nonfinite":"nan"},"role":"lv","threshold":{"_nonfinite":"+inf"}}],'
    '"pass":false,"scale":{"_nonfinite":"+inf"}}'
)

# Direction literals below were independently derived once from
# numpy.default_rng(seed).standard_normal(3), normalized, for seeds
# 200/201/202, then permuted storage->canonical.  They are fixed literals,
# not values generated by the serializer under test.
GOLDEN_RETRY_CURVATURE_RECORD = (
    '{"post_retry":{"K":[[-0.0,-0.0,-0.0],[-0.0,-0.0,-0.0],'
    '[-0.0,-0.0,-0.0]],"conditioning_ok":false,"directional_ok":true,'
    '"directional_records":[{"direction":[-0.5836491302931798,'
    '0.42866767201294514,-0.689635932705813],"error":0.0,'
    '"second_difference":0.0,"seed":200},{"direction":[-0.20989424792754147,'
    '0.6662640616058295,-0.7155673307938499],"error":0.0,'
    '"second_difference":0.0,"seed":201},{"direction":[-0.32628960814696545,'
    '0.8108396382808845,-0.48587464701075345],"error":0.0,'
    '"second_difference":0.0,"seed":202}],"eigenvalues":[-0.0,-0.0,-0.0],'
    '"grad_inf_norm":0.0,"logdet":{"_nonfinite":"-inf"},"logdet_by_h":['
    '{"h":0.0005,"logdet":{"_nonfinite":"-inf"}},{"h":0.001,'
    '"logdet":{"_nonfinite":"-inf"}},{"h":0.002,"logdet":{'
    '"_nonfinite":"-inf"}}],"logdet_stability_error":{"_nonfinite":"+inf"},'
    '"logdet_stable":false,"raw_hessian":[[-0.0,-0.0,-0.0],'
    '[-0.0,-0.0,-0.0],[-0.0,-0.0,-0.0]],"rcond":{"_nonfinite":"nan"},'
    '"reason":"logdet stability check failed; curvature is not strictly SPD; '
    'curvature retry optimization failed","spd":false,"stationary":true,'
    '"stop":true,"symmetry_error":0.0,"symmetry_ok":true,'
    '"u_star":[0.0,0.0,0.0]},"pre_retry":{"K":[[-0.0,-0.0,-0.0],'
    '[-0.0,-0.0,-0.0],[-0.0,-0.0,-0.0]],"conditioning_ok":false,'
    '"directional_ok":true,"directional_records":[{"direction":['
    '-0.5836491302931798,0.42866767201294514,-0.689635932705813],'
    '"error":0.0,"second_difference":0.0,"seed":200},{"direction":['
    '-0.20989424792754147,0.6662640616058295,-0.7155673307938499],'
    '"error":0.0,"second_difference":0.0,"seed":201},{"direction":['
    '-0.32628960814696545,0.8108396382808845,-0.48587464701075345],'
    '"error":0.0,"second_difference":0.0,"seed":202}],"eigenvalues":['
    '-0.0,-0.0,-0.0],"grad_inf_norm":0.0,"logdet":{"_nonfinite":"-inf"},'
    '"logdet_by_h":[{"h":0.0005,"logdet":{"_nonfinite":"-inf"}},'
    '{"h":0.001,"logdet":{"_nonfinite":"-inf"}},{"h":0.002,'
    '"logdet":{"_nonfinite":"-inf"}}],"logdet_stability_error":{'
    '"_nonfinite":"+inf"},"logdet_stable":false,"raw_hessian":['
    '[-0.0,-0.0,-0.0],[-0.0,-0.0,-0.0],[-0.0,-0.0,-0.0]],"rcond":{'
    '"_nonfinite":"nan"},"reason":"logdet stability check failed; curvature '
    'is not strictly SPD","spd":false,"stationary":true,"stop":true,'
    '"symmetry_error":0.0,"symmetry_ok":true,"u_star":[0.0,0.0,0.0]},'
    '"retry":{"conjuncts":{"gradient_shape_and_finite":true,'
    '"objective_finite":true,"output_shape_and_finite":true,'
    '"reported_success":false,"stationarity_within_bound":true,'
    '"status_zero":true},"fallback_fired":false,"fired":true,'
    '"positively_accepted":false,"telemetry":{"candidate_finite":true,'
    '"candidate_vector":[0.0,0.0,0.0],"gradient":[0.0,0.0,0.0],'
    '"message":"reported false","objective":-0.0,"observed_shape":[3],'
    '"reported_success":false,"required_shape":[3],"stationarity_norm":0.0,'
    '"status":0},"trigger":"spd_or_rcond_conditioning_failure"}}'
)


def _quadratic(diagonal=(1.0, 4.0, 9.0), center=None):
    matrix = np.diag(np.asarray(diagonal, dtype=np.float64))
    if center is None:
        center = np.zeros(3)
    center = np.asarray(center, dtype=np.float64)

    def g(u):
        delta = np.asarray(u, dtype=np.float64) - center
        return -0.5 * float(delta @ matrix @ delta)

    def grad(u):
        return -matrix @ (np.asarray(u, dtype=np.float64) - center)

    return g, grad


def _battery(nonfinite=False):
    references = (np.inf, -np.inf, np.nan) if nonfinite else (2.0, -3.0, 0.5)
    scale = np.inf if nonfinite else 3.0
    threshold = TOL_GRAD_ABS + TOL_GRAD_REL * scale
    return build_battery_record(
        [
            {
                "role": role,
                "fd_step": value,
                "reference_value": reference,
                "functional_value": value,
                "absolute_error": error,
                "threshold": threshold,
                "pass": False if nonfinite else True,
            }
            for role, reference, value, error in zip(
                ("ls", "os", "lv"),
                references,
                (np.nan, np.inf, -np.inf) if nonfinite else references,
                (np.inf, np.nan, -np.inf) if nonfinite else (0.0, 0.0, 0.0),
            )
        ]
    )


def _successful_optimizer():
    g, grad = _quadratic()
    result = gates.optimize_conditional_v2(
        lambda u: -g(u), lambda u: -grad(u), np.ones(3), -np.ones(3)
    )
    return result, build_two_start_optimizer_record(result, PERM)


def _normal_curvature():
    g, grad = _quadratic()
    result = gates.curvature_gate_v2(g, grad, np.zeros(3), STORAGE_ORDER)
    return result, build_curvature_record(result, PERM)


def _record_battery(monkeypatch):
    normal_opt_v2, normal_optimizer = _successful_optimizer()
    _normal_cur_v2, normal_curvature = _normal_curvature()
    mode_ref = build_warm_start_ref(
        {"kind": "mode_u"}, [0.0, 0.0, 0.0], "initial_mode_u"
    )
    previous_ref = build_warm_start_ref(
        {"kind": "accepted_node", "stage_id": "level0", "node_index": 0},
        [0.0, 0.0, 0.0],
        "carried_last_accepted_node",
    )
    current_ref = build_warm_start_ref(
        {"kind": "accepted_node", "stage_id": "level0", "node_index": 1},
        [0.0, 0.0, 0.0],
        "accepted_current_node",
    )
    normal_node = build_per_node_record(
        1,
        0.1,
        STORAGE_ORDER,
        mode_ref,
        current_ref,
        normal_optimizer,
        True,
        [0.0, 0.0, 0.0],
        _battery(),
        normal_curvature,
    )

    calls = 0

    def restart_warm(fun, x0, **kwargs):
        nonlocal calls
        calls += 1
        status = 2 if calls in {1, 3} else 0
        return OptimizeResult(
            x=np.zeros(3), status=status, success=status == 0, message="restart"
        )

    monkeypatch.setattr(gates, "minimize", restart_warm)
    restarted_v2 = gates.optimize_conditional_v2(
        lambda u: 0.0, lambda u: np.zeros(3), np.ones(3), -np.ones(3)
    )
    restarted_optimizer = build_two_start_optimizer_record(restarted_v2, PERM)

    def malformed_retry(fun, x0, **kwargs):
        return OptimizeResult(
            x=np.array([1.0, 2.0]), status=0, success=True, message="wrong shape"
        )

    monkeypatch.setattr(gates, "minimize", malformed_retry)
    indefinite_g, indefinite_grad = _quadratic((1.0, 4.0, -2.0))
    retried_v2 = gates.curvature_gate_v2(
        indefinite_g, indefinite_grad, np.zeros(3), STORAGE_ORDER
    )
    retried_curvature = build_curvature_record(retried_v2, PERM)
    fallback_node = build_per_node_record(
        2,
        0.2,
        STORAGE_ORDER,
        previous_ref,
        build_warm_start_ref(
            {"kind": "accepted_node", "stage_id": "level0", "node_index": 2},
            [0.0, 0.0, 0.0],
            "accepted_current_node",
        ),
        restarted_optimizer,
        True,
        [0.0, 0.0, 0.0],
        _battery(nonfinite=True),
        retried_curvature,
    )

    def nonfinite_attempt(fun, x0, **kwargs):
        return OptimizeResult(
            x=np.array([np.nan, np.inf, -np.inf]),
            status=0,
            success=True,
            message="all nonfinite",
        )

    monkeypatch.setattr(gates, "minimize", nonfinite_attempt)
    failed_v2 = gates.optimize_conditional_v2(
        lambda u: np.nan,
        lambda u: np.array([np.nan, np.inf, -np.inf]),
        np.ones(3),
        -np.ones(3),
    )
    failed_optimizer = build_two_start_optimizer_record(failed_v2, PERM)
    failed_node = build_per_node_record(
        3,
        0.3,
        STORAGE_ORDER,
        previous_ref,
        previous_ref,
        failed_optimizer,
        False,
        None,
    )
    assert normal_opt_v2["stop"] is False
    return [normal_node, fallback_node, failed_node]


_NUMERIC_REF_SHAPES = {
    "number_or_nonfinite": "",
    "vector_or_nonfinite": "[]",
    "matrix_or_nonfinite": "[][]",
    "canonical_vector3": "[]",
    "canonical_matrix3": "[][]",
    "finite_number": "",
    "count": "",
}


def _schema_numeric_paths(schema, path="$", seen=None):
    """Walk schema structure independently of all record builder code."""

    if seen is None:
        seen = set()
    paths = set()
    ref = schema.get("$ref")
    if ref is not None:
        assert ref.startswith("#/$defs/")
        name = ref.removeprefix("#/$defs/")
        if name in _NUMERIC_REF_SHAPES:
            paths.add(path + _NUMERIC_REF_SHAPES[name])
        elif (name, path) not in seen:
            paths |= _schema_numeric_paths(
                SCHEMA["$defs"][name], path, seen | {(name, path)}
            )
    if schema.get("type") in {"number", "integer"}:
        paths.add(path)
    const = schema.get("const")
    if isinstance(const, (int, float)) and not isinstance(const, bool):
        paths.add(path)
    for keyword in ("oneOf", "anyOf", "allOf"):
        for branch in schema.get(keyword, ()):
            paths |= _schema_numeric_paths(branch, path, seen)
    for name, subschema in schema.get("properties", {}).items():
        paths |= _schema_numeric_paths(subschema, f"{path}.{name}", seen)
    for index, subschema in enumerate(schema.get("prefixItems", ())):
        paths |= _schema_numeric_paths(subschema, f"{path}[{index}]", seen)
    items = schema.get("items")
    if isinstance(items, dict):
        paths |= _schema_numeric_paths(items, path + "[]", seen)
    return paths


def _emitted_numeric_leaves(value, path="$"):
    if is_nonfinite_sentinel(value):
        return {path}
    if isinstance(value, dict):
        result = set()
        for key, item in value.items():
            result |= _emitted_numeric_leaves(item, f"{path}.{key}")
        return result
    if isinstance(value, list):
        result = set()
        for index, item in enumerate(value):
            result |= _emitted_numeric_leaves(item, f"{path}[{index}]")
        return result
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return {path}
    return set()


def _pattern_matches(pattern, concrete):
    expression = re.escape(pattern).replace(r"\[\]", r"\[\d+\]")
    return re.fullmatch(expression, concrete) is not None


def test_schema_and_emitter_numeric_inventories_match_exactly(monkeypatch):
    schema_paths = _schema_numeric_paths({"$ref": "#/$defs/per_node_record"})
    emitted_paths = set()
    unmatched = set()
    for record in _record_battery(monkeypatch):
        for concrete in _emitted_numeric_leaves(record):
            matches = {path for path in schema_paths if _pattern_matches(path, concrete)}
            if not matches:
                unmatched.add(concrete)
            emitted_paths |= matches
    assert unmatched == set(), f"numeric fields emitted outside the schema: {unmatched}"
    assert emitted_paths == schema_paths, (
        f"schema-only={schema_paths - emitted_paths}; "
        f"emitter-only={emitted_paths - schema_paths}"
    )


@pytest.mark.parametrize(
    ("value", "golden"),
    [(-np.inf, GOLDEN_NEG_INF), (np.inf, GOLDEN_POS_INF), (np.nan, GOLDEN_NAN)],
)
def test_each_nonfinite_kind_matches_handwritten_golden(value, golden):
    assert canonical_dumps({"value": encode_float(value)}) == golden
    assert json.loads(golden) == {"value": encode_float(value)}


def test_nonfinite_vector_matches_handwritten_golden():
    instance = {"vector": encode_vector([-np.inf, np.inf, np.nan])}
    assert canonical_dumps(instance) == GOLDEN_VECTOR
    assert json.loads(GOLDEN_VECTOR) == instance


def test_full_optimizer_record_matches_handwritten_golden(monkeypatch):
    calls = 0

    def fixed_optimizer(fun, x0, **kwargs):
        nonlocal calls
        calls += 1
        candidate = (
            np.array([0.0, 1.0, 0.5])
            if calls == 1
            else np.array([1.0, 0.0, 0.5])
        )
        return OptimizeResult(
            x=candidate,
            status=0,
            success=True,
            message=f"fixed {calls}",
        )

    monkeypatch.setattr(gates, "minimize", fixed_optimizer)
    result = gates.optimize_conditional_v2(
        lambda u: np.inf if np.asarray(u)[0] == 0.0 else -0.5,
        lambda u: (
            np.array([0.0, -np.inf, np.nan])
            if np.asarray(u)[0] == 0.0
            else np.array([-0.0, -0.0, -0.0])
        ),
        np.ones(3),
        -np.ones(3),
    )
    assert result["restart_count"] == 0
    record = build_two_start_optimizer_record(result, PERM)
    validate_fragment(record, "#/$defs/two_start_optimizer_record")
    assert canonical_dumps(record) == GOLDEN_TWO_START_OPTIMIZER_RECORD


def test_full_battery_record_matches_handwritten_golden():
    record = _battery(nonfinite=True)
    validate_fragment(record, "#/$defs/battery_record")
    assert canonical_dumps(record) == GOLDEN_BATTERY_RECORD


def test_nonfinite_records_validate_and_round_trip(monkeypatch):
    records = _record_battery(monkeypatch)
    for record in records:
        validate_fragment(record, "#/$defs/per_node_record")
        serialized = canonical_dumps(record)
        assert json.loads(serialized) == record
        assert not re.search(r"(?<![\w\"])(?:NaN|Infinity|-Infinity)(?![\w\"])", serialized)


def test_zero_hessian_forces_logdet_neg_inf_rcond_nan_and_false_success(monkeypatch):
    def false_success(fun, x0, **kwargs):
        return OptimizeResult(x=x0, status=0, success=False, message="reported false")

    monkeypatch.setattr(gates, "minimize", false_success)
    g, grad = _quadratic((0.0, 0.0, 0.0))
    result = gates.curvature_gate_v2(g, grad, np.zeros(3), STORAGE_ORDER)
    record = build_curvature_record(result, PERM)
    validate_fragment(record, "#/$defs/curvature_record")
    pre = record["pre_retry"]
    assert pre["logdet"] == {"_nonfinite": "-inf"}
    assert pre["rcond"] == {"_nonfinite": "nan"}
    assert record["retry"]["telemetry"]["reported_success"] is False
    assert record["retry"]["positively_accepted"] is False
    assert canonical_dumps(record) == GOLDEN_RETRY_CURVATURE_RECORD


@pytest.mark.parametrize("objective", [-np.inf, np.inf, np.nan])
def test_nonfinite_objectives_and_gradients_emit_valid_optimizer_records(
    monkeypatch, objective
):
    def fixed_result(fun, x0, **kwargs):
        return OptimizeResult(x=np.zeros(3), status=0, success=True, message="fixed")

    monkeypatch.setattr(gates, "minimize", fixed_result)
    result = gates.optimize_conditional_v2(
        lambda u: -objective,
        lambda u: np.array([np.nan, np.inf, -np.inf]),
        np.ones(3),
        -np.ones(3),
    )
    record = build_two_start_optimizer_record(result, PERM)
    validate_fragment(record, "#/$defs/two_start_optimizer_record")
    serialized = canonical_dumps(record)
    assert "_nonfinite" in serialized
    assert json.loads(serialized) == record


def test_invalid_nonfinite_and_closed_schema_cases_fail(monkeypatch):
    record = _record_battery(monkeypatch)[0]
    unknown = copy.deepcopy(record)
    unknown["unknown"] = 1.0
    with pytest.raises(ValidationError):
        validate_fragment(unknown, "#/$defs/per_node_record")

    malformed = copy.deepcopy(record)
    malformed["optimizer"]["g_star"] = {"_nonfinite": "infinity"}
    with pytest.raises(ValidationError):
        validate_fragment(malformed, "#/$defs/per_node_record")

    finite_only = copy.deepcopy(record)
    finite_only["noise"] = {"_nonfinite": "+inf"}
    with pytest.raises(ValidationError):
        validate_fragment(finite_only, "#/$defs/per_node_record")

    raw = json.loads('{"value":NaN}')
    with pytest.raises(ValueError):
        canonical_dumps(raw)
